name: Build Linux

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          qt6-base-dev \
          qt6-declarative-dev \
          cmake \
          build-essential \
          git

    - name: Build Paho MQTT C
      run: |
        git clone https://github.com/eclipse/paho.mqtt.c.git
        cd paho.mqtt.c
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DPAHO_BUILD_STATIC=ON
        cmake --build .
        sudo cmake --install . --prefix "${{ github.workspace }}/paho-install"

    - name: Build Paho MQTT C++
      run: |
        git clone https://github.com/eclipse/paho.mqtt.cpp.git
        cd paho.mqtt.cpp
        mkdir build && cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DPAHO_BUILD_STATIC=ON \
          -DCMAKE_PREFIX_PATH="${{ github.workspace }}/paho-install"
        cmake --build .
        sudo cmake --install . --prefix "${{ github.workspace }}/paho-install"

    - name: Configure Qt Project
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH="${{ github.workspace }}/paho-install"

    - name: Build Qt Project
      run: |
        cd build
        cmake --build .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sky114DebugApplication-linux
        path: build/appSky114DebugApplication
